services:
  wartable:
    build: .
    restart: unless-stopped
    runtime: nvidia
    ports:
      - "9400:9400"
    volumes:
      - ${HOME}/.wartable:/root/.wartable
      - /home:/home
      - /root:/root
      - /tmp:/tmp
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility]
